# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a94v8w;7bgy6awh
      MYSQL_USER: admin
      MYSQL_PASSWORD: a94v8w;7bgy6awh
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
